apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: rsvpapp
  description: RSVPAPP Application
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: marketing-team
  domain: rsvpapp-cloud-domain
