apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: my-rsvpapp
    apps.tanzu.vmware.com/workload-type: web
  name: my-rsvpapp
  namespace: rsvpapp
spec:
  params:
  - name: gitops_ssh_secret
    value: git-ssh
  env:
  - name: MONGODB_HOST
    value: mongodb
  source:
    git:
      ref:
        branch: main
      url: https://github.com/dbha/myrsvpapp