---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rsvp-web-pvc
  namespace: rsvpapp
  labels:
    app: rsvp-web
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
