apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: marketing-org
  description: The Default Organization
  links:
    - url: https://tanzu.vmware.com/support
      title: Tanzu Support Website
spec:
  type: organization
  profile:
    displayName: marketing Organization
    email: operator@tap.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [marketing-team]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: marketing-group
  description: A marketing Group Location
spec:
  targets:
    - ./marketing-team.yaml
    - ./guest-user.yaml
