apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: marketing-team
  description: marketing Team
spec:
  type: team
  profile:
    displayName: marketing Team
    email: marketing@tap.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: marketing-org
  children: []


